// 共享工具元数据，供首页、搜索和工具注册复用。
export const TOOLS = [
  ['universal-encoding','UNI','统一编解码','统一支持 URL、Base、Hex、Unicode、ASCII、二进制、八进制、十进制等格式互转','编解码'],
  ['jwt','JWT','JWT 结构编解码','JWT JSON 结构与 Token 互转，保留 signature 第三段','编解码'],
  ['char-escape','ESC','特殊字符转义','JSON 字符串场景下的特殊字符转义与反转义','编解码'],
  ['md5','MD5','MD5 哈希','计算 MD5 消息摘要，输出 128-bit 结果（不建议用于安全场景）','哈希算法'],
  ['sha','SHA','SHA 哈希','在 SHA-1 / SHA-256 / SHA-384 / SHA-512 之间切换（SHA-1 不建议）','哈希算法'],
  ['sm3','SM3','SM3 哈希','GB/T 32905-2016 国密 SM3 哈希算法','哈希算法'],
  ['hmac','HMC','HMAC 签名','HMAC 消息认证码，确保完整性和真实性','加解密'],
  ['aes','AES','AES 加解密','对称加密 AES，支持 CBC/GCM/CTR 模式','加解密'],
  ['des','DES','DES/3DES','DES 对称加解密（高风险，仅作演示）','加解密'],
  ['sm4','SM4','SM4 加解密','GB/T 32907-2016 国密 SM4 对称加密','加解密'],
  ['rsa','RSA','RSA 加解密','非对称加密 RSA，公钥加密私钥解密','加解密'],
  ['sm2','SM2','SM2 加解密','GB/T 32918-2016 国密 SM2 椭圆曲线算法','加解密'],
  ['chacha20','C20','ChaCha20','RFC 8439 高性能流密码','加解密'],
  ['uuid','UID','UUID 生成','生成多种版本的 UUID 唯一标识符','数据生成'],
  ['password','PWD','密码生成','生成安全的随机密码，支持多种强度','数据生成'],
  ['qrcode','QR','二维码生成','生成文本或 WiFi 配置的二维码','数据生成'],
  ['lorem','LOR','占位文本（Lorem Ipsum）','生成占位文本，可自定义段落和句子数','数据生成'],
  ['timestamp','TS','时间戳转换','在 UNIX 时间戳和日期时间格式之间转换','数据转换'],
  ['time-interval','INT','时间间隔','计算两个日期时间之间的间隔','数据转换'],
  ['color','CLR','颜色转换','HEX/RGB/HSL/CMYK 颜色格式互转','数据转换'],
  ['data-format','DAT','数据格式转换','JSON/XML/CSV/YAML 结构化数据互转','数据转换'],
  ['case-convert','CAS','字符格式化','驼峰/帕斯卡/下划线等命名格式化','格式化'],
  ['regex','REG','正则测试','在线测试正则表达式匹配效果','格式化'],
  ['code-format','FMT','代码格式化','格式化代码，支持 JSON/HTML/CSS','格式化'],
  ['code-minify','MIN','代码压缩','压缩精简代码，支持 JS/CSS/HTML','格式化'],
  ['text-diff','DIF','文本对比','比较两段文本的差异并高亮显示','数据分析'],
  ['text-stats','CNT','文本统计','统计分析文本中各类字符的数量','数据分析'],
  ['ua-parser','UA','UA 解析','解析 User-Agent 字符串，识别浏览器和系统','数据分析'],
  ['key-event','KEY','键盘事件','实时查看 KeyboardEvent 的 key/code 等属性','数据分析'],
  // ['svg-optimize','SVG','SVG 优化','清理并压缩 SVG 文件，移除冗余元素','图像'],
];
